// Generated by scripts/seed-whitelist-codegen.ts. Do not edit by hand once
// capture fixtures are available.
//
// Capture flow:
//   1. CERELAY_CAPTURE_SEED=/tmp/seed.json npm run start
//   2. Run a normal Claude Code session against a real ~/.claude tree.
//   3. node scripts/seed-whitelist-codegen.ts /tmp/seed.json > server/src/seed-whitelist.ts
//   4. Commit the generated fixture.

import type { SyncPlan } from "./sync-plan.js";

export const SEED_WHITELIST: Readonly<SyncPlan> = Object.freeze({
  scopes: {
    "claude-home": Object.freeze({
      subtrees: Object.freeze([]),
      files: Object.freeze([]),
      knownMissing: Object.freeze([]),
    }),
    "claude-json": Object.freeze({
      subtrees: Object.freeze([{ relPath: "", maxDepth: 0 }]),
      files: Object.freeze([]),
      knownMissing: Object.freeze([]),
    }),
  },
}) as unknown as Readonly<SyncPlan>;
